### ISSUE TITLE
Create classes for Vector and Matrix math

### ISSUE THREAD

**Issue by frans-johansson** [frans-johansson/rar-aya#1]
We need to be able to handle three-component and possibly two-component vectors, primarily of floats, as well as 4x4 matrices.

_There is currently a utils package within which a subpackage for math could be created._

**TODO for matrices:**
- Identity
- Rotation (preferably euler rotation, but methods for individual axes would suffice)
- Translation
- Scale
- Multiplication (preferably in a fluid way such that multiplications can be stringed together easily)

**TODO for vectors:**
- Dot product
- Cross product
- Reflections (Maybe?)

**Comment by ZeMaster1** [comment]
#e68af6be72dbddeb722445c939093ab903eb3d70
